name: CD

on:
    push:
        branches:
            - sc-505-refactor-deployment-scripts
env:
  ALCHEMY_ID: ${{ secrets.ALCHEMY_ID }}
  INFURA_ID: ${{ secrets.INFURA_ID }}
  PROVIDER_URLS: ${{ vars.PROVIDER_URLS }}
  GELOTO_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
  MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
  GNOSIS_CHAIN_RPC_URL: ${{ secrets.GNOSIS_CHAIN_RPC_URL }}
  SPARK_INFO_SLACK_WEBHOOK_URL: ${{ secrets.SPARK_INFO_SLACK_WEBHOOK_URL }}
  GELATO_KEEPERS_ETHERSCAN_API_KEY: ${{ secrets.GELATO_KEEPERS_ETHERSCAN_API_KEY }}

jobs:
  deploy:
    strategy:
      fail-fast: true

    environment: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install yarn
        run: npm install -g yarn

      - name: Run yarn install
        run: yarn install

      - name: Upload code to IPFS
        run: yarn gelato:ipfs

      - name: Deploy keepers
        run: yarn gelato:deploy -d -n
