name: CI

on:
    pull_request:
    push:
        branches:
            - master
env:
  ALCHEMY_ID: ${{ secrets.ALCHEMY_ID }}
  INFURA_ID: ${{ secrets.INFURA_ID }}
  PROVIDER_URLS: ${{ vars.PROVIDER_URLS }}

jobs:
  check:
    strategy:
      fail-fast: true

    environment: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install yarn
        run: npm install -g yarn

      - name: Run yarn install
        run: yarn install

      - name: Run linter
        run: yarn lint

      - name: Run tests
        run: yarn test
